// Generated by: main
// TypeWriter: controller_test
// Directive: +gen on Session

package sessions

import (
	"errors"
	"net/http"
	"testing"

	"github.com/Solher/auth-scaffold/apierrors"
	"github.com/Solher/auth-scaffold/infrastructure"
	"github.com/Solher/auth-scaffold/interfaces"
	"github.com/Solher/auth-scaffold/utils"
	"github.com/julienschmidt/httprouter"
	. "github.com/smartystreets/goconvey/convey"
	"github.com/unrolled/render"
)

type stubRender struct {
	renderer *render.Render
}

func newStubRender() *stubRender {
	return &stubRender{renderer: render.New()}
}

func (r *stubRender) JSONError(w http.ResponseWriter, status int, apiError *apierrors.APIError, err error) {
	r.renderer.JSON(w, status, apierrors.Make(*apiError, status, err))
}

func (r *stubRender) JSON(w http.ResponseWriter, status int, object interface{}) {
	r.renderer.JSON(w, status, object)
}

type stubInteractor struct {
	ThrowErrors bool
}

func (i *stubInteractor) Create(sessions []Session) ([]Session, error) {
	if i.ThrowErrors {
		return nil, errors.New("error")
	}

	for i := range sessions {
		sessions[i].ID = i + 1
	}

	return sessions, nil
}

func (i *stubInteractor) Find(filter *interfaces.Filter) ([]Session, error) {
	sessions := []Session{
		{
			FirstName: "Fabien",
			LastName:  "Herfray",
		},
		{
			FirstName: "Thomas",
			LastName:  "Hourlier",
		},
	}

	if i.ThrowErrors {
		return nil, errors.New("error")
	}

	return sessions, nil
}

func (i *stubInteractor) FindByID(id int, filter *interfaces.Filter) (*Session, error) {
	sessions := []Session{
		{
			FirstName: "Fabien",
			LastName:  "Herfray",
		},
	}

	if i.ThrowErrors || id-1 > 0 {
		return nil, errors.New("error")
	}

	return &sessions[id-1], nil
}

func (i *stubInteractor) Upsert(sessions []Session) ([]Session, error) {
	if i.ThrowErrors {
		return nil, errors.New("error")
	}

	for i := range sessions {
		if sessions[i].ID == 0 {
			switch {
			case sessions[i-1].ID != 0:
				sessions[i].ID = sessions[i-1].ID
			default:
				sessions[i].ID = i + 1
			}
		}
	}

	return sessions, nil
}

func (i *stubInteractor) DeleteAll(filter *interfaces.Filter) error {
	if i.ThrowErrors {
		return errors.New("error")
	}

	return nil
}

func (i *stubInteractor) DeleteByID(id int) error {
	if i.ThrowErrors {
		return errors.New("error")
	}

	return nil
}

func TestController(t *testing.T) {
	interactor := &stubInteractor{}
	render := infrastructure.NewRender()
	routes := interfaces.NewRouteDirectory()

	controller := NewController(interactor, render, routes)
	key := interfaces.NewDirectoryKey(controller)

	Convey("Testing sessions controller...", t, func() {
		sessions := []Session{
			{
				FirstName: "Fabien",
				LastName:  "Herfray",
			},
			{
				FirstName: "Thomas",
				LastName:  "Hourlier",
			},
		}

		interactor.ThrowErrors = false

		Convey("Should be able to create sessions.", func() {
			route := routes[key.For("Create")]
			res := interfaces.MockHTTPRequest(route, utils.MarshalToStr(sessions), "", nil)
			utils.Unmarshal(res, &sessions)

			So(sessions[0].ID, ShouldNotEqual, 0)
			So(sessions[1].ID, ShouldNotEqual, 0)

			res = interfaces.MockHTTPRequest(route, "string", "", nil)
			So(interfaces.GetErrorCode(res), ShouldEqual, apierrors.BodyDecodingError.ErrorCode)

			res = interfaces.MockHTTPRequest(route, "", "", nil)
			So(interfaces.GetErrorCode(res), ShouldEqual, apierrors.BodyDecodingError.ErrorCode)

			interactor.ThrowErrors = true

			res = interfaces.MockHTTPRequest(route, utils.MarshalToStr(sessions), "", nil)
			So(interfaces.GetErrorCode(res), ShouldEqual, apierrors.InternalServerError.ErrorCode)
		})

		Convey("Should be able to find sessions.", func() {
			route := routes[key.For("Find")]

			res := interfaces.MockHTTPRequest(route, "", "", nil)
			So(res, ShouldEqual, utils.MarshalToStr(sessions))

			res = interfaces.MockHTTPRequest(route, "", "toto", nil)
			So(interfaces.GetErrorCode(res), ShouldEqual, apierrors.FilterDecodingError.ErrorCode)

			res = interfaces.MockHTTPRequest(route, "", "{\"limit\": 1}", nil)
			So(interfaces.GetErrorCode(res), ShouldNotEqual, apierrors.FilterDecodingError.ErrorCode)

			interactor.ThrowErrors = true

			res = interfaces.MockHTTPRequest(route, "", "", nil)
			So(interfaces.GetErrorCode(res), ShouldEqual, apierrors.InternalServerError.ErrorCode)
		})

		Convey("Should be able to find session by id.", func() {
			route := routes[key.For("FindByID")]

			params := httprouter.Params{
				{
					Key:   "id",
					Value: "1",
				},
			}

			res := interfaces.MockHTTPRequest(route, "", "", params)
			So(res, ShouldEqual, utils.MarshalToStr(sessions[0]))

			params[0].Value = "2"
			res = interfaces.MockHTTPRequest(route, "", "", params)
			So(interfaces.GetErrorCode(res), ShouldEqual, apierrors.Unauthorized.ErrorCode)

			params[0].Value = ""
			res = interfaces.MockHTTPRequest(route, "", "", params)
			So(interfaces.GetErrorCode(res), ShouldEqual, apierrors.InvalidPathParams.ErrorCode)

			params[0].Value = "toto"
			res = interfaces.MockHTTPRequest(route, "", "", params)
			So(interfaces.GetErrorCode(res), ShouldEqual, apierrors.InvalidPathParams.ErrorCode)

			interactor.ThrowErrors = true

			params[0].Value = "1"
			res = interfaces.MockHTTPRequest(route, "", "", params)
			So(interfaces.GetErrorCode(res), ShouldEqual, apierrors.Unauthorized.ErrorCode)
		})

		Convey("Should be able to upsert sessions.", func() {
			route := routes[key.For("Upsert")]
			sessions[0].ID = 3

			res := interfaces.MockHTTPRequest(route, utils.MarshalToStr(sessions), "", nil)
			utils.Unmarshal(res, &sessions)

			So(sessions[0].ID, ShouldEqual, 3)
			So(sessions[1].ID, ShouldNotEqual, 0)

			res = interfaces.MockHTTPRequest(route, "string", "", nil)
			So(interfaces.GetErrorCode(res), ShouldEqual, apierrors.BodyDecodingError.ErrorCode)

			res = interfaces.MockHTTPRequest(route, "", "", nil)
			So(interfaces.GetErrorCode(res), ShouldEqual, apierrors.BodyDecodingError.ErrorCode)

			interactor.ThrowErrors = true

			res = interfaces.MockHTTPRequest(route, utils.MarshalToStr(sessions), "", nil)
			So(interfaces.GetErrorCode(res), ShouldEqual, apierrors.InternalServerError.ErrorCode)
		})

		Convey("Should be able to delete sessions.", func() {
			route := routes[key.For("DeleteAll")]

			res := interfaces.MockHTTPRequest(route, utils.MarshalToStr(sessions), "", nil)
			So(res, ShouldEqual, "null")

			res = interfaces.MockHTTPRequest(route, "", "toto", nil)
			So(interfaces.GetErrorCode(res), ShouldEqual, apierrors.FilterDecodingError.ErrorCode)

			res = interfaces.MockHTTPRequest(route, "", "{\"limit\": 1}", nil)
			So(interfaces.GetErrorCode(res), ShouldNotEqual, apierrors.FilterDecodingError.ErrorCode)

			interactor.ThrowErrors = true

			res = interfaces.MockHTTPRequest(route, utils.MarshalToStr(sessions), "", nil)
			So(interfaces.GetErrorCode(res), ShouldEqual, apierrors.InternalServerError.ErrorCode)
		})

		Convey("Should be able to delete session by id.", func() {
			route := routes[key.For("DeleteByID")]

			params := httprouter.Params{
				{
					Key:   "id",
					Value: "1",
				},
			}

			res := interfaces.MockHTTPRequest(route, "", "", params)
			So(res, ShouldEqual, "null")

			params[0].Value = "2"
			res = interfaces.MockHTTPRequest(route, "", "", params)
			So(res, ShouldEqual, "null")

			params[0].Value = ""
			res = interfaces.MockHTTPRequest(route, "", "", params)
			So(interfaces.GetErrorCode(res), ShouldEqual, apierrors.InvalidPathParams.ErrorCode)

			params[0].Value = "toto"
			res = interfaces.MockHTTPRequest(route, "", "", params)
			So(interfaces.GetErrorCode(res), ShouldEqual, apierrors.InvalidPathParams.ErrorCode)

			interactor.ThrowErrors = true

			params[0].Value = "1"
			res = interfaces.MockHTTPRequest(route, "", "", params)
			So(interfaces.GetErrorCode(res), ShouldEqual, apierrors.Unauthorized.ErrorCode)
		})
	})
}
