// Generated by: main
// TypeWriter: interactor
// Directive: +gen on User

package users

import "github.com/Solher/auth-scaffold/interfaces"

type UserRepository interface {
	Create(users []User) ([]User, error)
	Find(filter *interfaces.Filter) ([]User, error)
	FindByID(id int) (*User, error)
	Upsert(users []User) ([]User, error)
	DeleteAll(filter *interfaces.Filter) error
	DeleteByID(id int) error
}

type Interactor struct {
	repo UserRepository
}

func NewInteractor(repo UserRepository) *Interactor {
	return &Interactor{repo: repo}
}

func (i *Interactor) Create(users []User) ([]User, error) {
	users, err := i.repo.Create(users)
	return users, err
}

func (i *Interactor) Find(filter *interfaces.Filter) ([]User, error) {
	users, err := i.repo.Find(filter)
	return users, err
}

func (i *Interactor) FindByID(id int) (*User, error) {
	user, err := i.repo.FindByID(id)
	return user, err
}

func (i *Interactor) Upsert(users []User) ([]User, error) {
	users, err := i.repo.Upsert(users)
	return users, err
}

func (i *Interactor) DeleteAll(filter *interfaces.Filter) error {
	err := i.repo.DeleteAll(filter)
	return err
}

func (i *Interactor) DeleteByID(id int) error {
	err := i.repo.DeleteByID(id)
	return err
}
