// Generated by: main
// TypeWriter: repository
// Directive: +gen on Email

package emails

import "github.com/Solher/auth-scaffold/interfaces"

type Repository struct {
	store interfaces.GormStore
}

func NewRepository(store interfaces.GormStore) *Repository {
	return &Repository{store: store}
}

func (r *Repository) Create(emails []Email) ([]Email, error) {
	db := r.store.GetDB()
	transaction := db.Begin()

	for i, email := range emails {
		err := db.Create(&email).Error
		if err != nil {
			transaction.Rollback()
			return nil, err
		}

		emails[i] = email
	}

	transaction.Commit()
	return emails, nil
}

func (r *Repository) Find(filter *interfaces.Filter) ([]Email, error) {
	query, err := r.store.BuildQuery(filter)
	if err != nil {
		return nil, err
	}

	emails := []Email{}

	err = query.Find(&emails).Error
	if err != nil {
		return nil, err
	}

	return emails, nil
}

func (r *Repository) FindByID(id int, filter *interfaces.Filter) (*Email, error) {
	query, err := r.store.BuildQuery(filter)
	if err != nil {
		return nil, err
	}

	email := Email{}

	err = query.First(&email, id).Error
	if err != nil {
		return nil, err
	}

	return &email, nil
}

func (r *Repository) Upsert(emails []Email) ([]Email, error) {
	db := r.store.GetDB()
	transaction := db.Begin()

	for i, email := range emails {
		if email.ID != 0 {
			oldUser := Email{}

			err := db.First(&oldUser, email.ID).Updates(email).Error
			if err != nil {
				transaction.Rollback()
				return nil, err
			}
		} else {
			err := db.Create(&email).Error
			if err != nil {
				transaction.Rollback()
				return nil, err
			}
		}

		emails[i] = email
	}

	transaction.Commit()
	return emails, nil
}

func (r *Repository) DeleteAll(filter *interfaces.Filter) error {
	query, err := r.store.BuildQuery(filter)
	if err != nil {
		return err
	}

	err = query.Delete(Email{}).Error
	if err != nil {
		return err
	}

	return nil
}

func (r *Repository) DeleteByID(id int) error {
	db := r.store.GetDB()

	err := db.Delete(&Email{ID: id}).Error
	if err != nil {
		return err
	}

	return nil
}
