// Generated by: main
// TypeWriter: interactor_test
// Directive: +gen on Email

package emails

import (
	"testing"

	"github.com/Solher/auth-scaffold/interfaces"
	. "github.com/smartystreets/goconvey/convey"
)

type stubRepository struct{}

func (r *stubRepository) Create(emails []Email) ([]Email, error) {
	return emails, nil
}

func (r *stubRepository) Find(filter *interfaces.Filter) ([]Email, error) {
	return []Email{}, nil
}

func (r *stubRepository) FindByID(id int, filter *interfaces.Filter) (*Email, error) {
	return &Email{}, nil
}

func (r *stubRepository) Upsert(emails []Email) ([]Email, error) {
	return emails, nil
}

func (r *stubRepository) DeleteAll(filter *interfaces.Filter) error {
	return nil
}

func (r *stubRepository) DeleteByID(id int) error {
	return nil
}

func TestInteractor(t *testing.T) {
	repo := &stubRepository{}
	interactor := NewInteractor(repo)

	Convey("Testing emails interactor...", t, func() {
		Convey("Should be able to create emails.", func() {
			emails := []Email{}
			_, err := interactor.Create(emails)

			So(err, ShouldBeNil)
		})

		Convey("Should be able to find emails.", func() {
			_, err := interactor.Find(nil)

			So(err, ShouldBeNil)
		})

		Convey("Should be able to find a email by id.", func() {
			_, err := interactor.FindByID(1, nil)

			So(err, ShouldBeNil)
		})

		Convey("Should be able to upsert emails.", func() {
			emails := []Email{}
			_, err := interactor.Upsert(emails)

			So(err, ShouldBeNil)
		})

		Convey("Should be able to delete emails.", func() {
			err := interactor.DeleteAll(nil)
			So(err, ShouldBeNil)
		})

		Convey("Should be able to delete a email by id.", func() {
			err := interactor.DeleteByID(1)
			So(err, ShouldBeNil)
		})
	})
}
