// Generated by: main
// TypeWriter: hooks
// Directive: +gen on Account

package ressources

import (
	"time"

	"github.com/Solher/zest/domain"
)

func (i *AccountInter) BeforeCreate(account *domain.Account) error {
	account.ID = 0
	account.CreatedAt = time.Time{}
	account.UpdatedAt = time.Time{}

	err := account.ScopeModel()
	if err != nil {
		return err
	}

	return nil
}

func (i *AccountInter) AfterCreate(account *domain.Account) error {
	return nil
}

func (i *AccountInter) BeforeUpdate(account *domain.Account) error {
	account.ID = 0
	account.CreatedAt = time.Time{}
	account.UpdatedAt = time.Time{}

	err := account.ScopeModel()
	if err != nil {
		return err
	}

	return nil
}

func (i *AccountInter) AfterUpdate(account *domain.Account) error {
	return nil
}

func (i *AccountInter) BeforeDelete(account *domain.Account) error {
	return nil
}

func (i *AccountInter) AfterDelete(account *domain.Account) error {
	return nil
}
