// Generated by: main
// TypeWriter: hooks
// Directive: +gen on Acl

package ressources

import (
	"time"

	"github.com/Solher/zest/domain"
)

func (i *AclInter) BeforeCreate(acl *domain.Acl) error {
	acl.ID = 0
	acl.CreatedAt = time.Time{}
	acl.UpdatedAt = time.Time{}

	err := acl.ScopeModel()
	if err != nil {
		return err
	}

	return nil
}

func (i *AclInter) AfterCreate(acl *domain.Acl) error {
	return nil
}

func (i *AclInter) BeforeUpdate(acl *domain.Acl) error {
	acl.ID = 0
	acl.CreatedAt = time.Time{}
	acl.UpdatedAt = time.Time{}

	err := acl.ScopeModel()
	if err != nil {
		return err
	}

	return nil
}

func (i *AclInter) AfterUpdate(acl *domain.Acl) error {
	return nil
}

func (i *AclInter) BeforeDelete(acl *domain.Acl) error {
	return nil
}

func (i *AclInter) AfterDelete(acl *domain.Acl) error {
	return nil
}
