// Generated by: main
// TypeWriter: hooks
// Directive: +gen on AclMapping

package ressources

import (
	"time"

	"github.com/Solher/zest/domain"
)

func (i *AclMappingInter) BeforeCreate(aclmapping *domain.AclMapping) error {
	aclmapping.ID = 0
	aclmapping.CreatedAt = time.Time{}
	aclmapping.UpdatedAt = time.Time{}

	err := aclmapping.ScopeModel()
	if err != nil {
		return err
	}

	return nil
}

func (i *AclMappingInter) AfterCreate(aclmapping *domain.AclMapping) error {
	return nil
}

func (i *AclMappingInter) BeforeUpdate(aclmapping *domain.AclMapping) error {
	aclmapping.ID = 0
	aclmapping.CreatedAt = time.Time{}
	aclmapping.UpdatedAt = time.Time{}

	err := aclmapping.ScopeModel()
	if err != nil {
		return err
	}

	return nil
}

func (i *AclMappingInter) AfterUpdate(aclmapping *domain.AclMapping) error {
	return nil
}

func (i *AclMappingInter) BeforeDelete(aclmapping *domain.AclMapping) error {
	return nil
}

func (i *AclMappingInter) AfterDelete(aclmapping *domain.AclMapping) error {
	return nil
}
