// Generated by: main
// TypeWriter: repository
// Directive: +gen on AclMapping

package ressources

import (
	"strings"

	"github.com/Solher/auth-scaffold/domain"
	"github.com/Solher/auth-scaffold/interfaces"
	"github.com/Solher/auth-scaffold/internalerrors"
)

type AclMappingRepo struct {
	store interfaces.AbstractGormStore
}

func NewAclMappingRepo(store interfaces.AbstractGormStore) *AclMappingRepo {
	return &AclMappingRepo{store: store}
}

func (r *AclMappingRepo) Create(aclmappings []domain.AclMapping) ([]domain.AclMapping, error) {
	db := r.store.GetDB()
	transaction := db.Begin()

	for i, aclmapping := range aclmappings {
		err := db.Create(&aclmapping).Error
		if err != nil {
			transaction.Rollback()

			if strings.Contains(err.Error(), "constraint") {
				return nil, internalerrors.NewViolatedConstraint(err.Error())
			} else {
				return nil, internalerrors.DatabaseError
			}
		}

		aclmappings[i] = aclmapping
	}

	transaction.Commit()
	return aclmappings, nil
}

func (r *AclMappingRepo) CreateOne(aclmapping *domain.AclMapping) (*domain.AclMapping, error) {
	db := r.store.GetDB()

	err := db.Create(aclmapping).Error
	if err != nil {
		if strings.Contains(err.Error(), "constraint") {
			return nil, internalerrors.NewViolatedConstraint(err.Error())
		} else {
			return nil, internalerrors.DatabaseError
		}
	}

	return aclmapping, nil
}

func (r *AclMappingRepo) Find(filter *interfaces.Filter) ([]domain.AclMapping, error) {
	query, err := r.store.BuildQuery(filter)
	if err != nil {
		return nil, internalerrors.DatabaseError
	}

	aclmappings := []domain.AclMapping{}

	err = query.Find(&aclmappings).Error
	if err != nil {
		return nil, internalerrors.DatabaseError
	}

	return aclmappings, nil
}

func (r *AclMappingRepo) FindByID(id int, filter *interfaces.Filter) (*domain.AclMapping, error) {
	query, err := r.store.BuildQuery(filter)
	if err != nil {
		return nil, internalerrors.DatabaseError
	}

	aclmapping := domain.AclMapping{}

	err = query.First(&aclmapping, id).Error
	if err != nil {
		return nil, internalerrors.DatabaseError
	}

	return &aclmapping, nil
}

func (r *AclMappingRepo) Upsert(aclmappings []domain.AclMapping) ([]domain.AclMapping, error) {
	db := r.store.GetDB()
	transaction := db.Begin()

	for i, aclmapping := range aclmappings {
		if aclmapping.ID != 0 {
			oldUser := domain.AclMapping{}

			err := db.First(&oldUser, aclmapping.ID).Updates(aclmapping).Error
			if err != nil {
				transaction.Rollback()

				if strings.Contains(err.Error(), "constraint") {
					return nil, internalerrors.NewViolatedConstraint(err.Error())
				} else {
					return nil, internalerrors.DatabaseError
				}
			}
		} else {
			err := db.Create(&aclmapping).Error
			if err != nil {
				transaction.Rollback()

				if strings.Contains(err.Error(), "constraint") {
					return nil, internalerrors.NewViolatedConstraint(err.Error())
				} else {
					return nil, internalerrors.DatabaseError
				}
			}
		}

		aclmappings[i] = aclmapping
	}

	transaction.Commit()
	return aclmappings, nil
}

func (r *AclMappingRepo) UpsertOne(aclmapping *domain.AclMapping) (*domain.AclMapping, error) {
	db := r.store.GetDB()

	if aclmapping.ID != 0 {
		oldUser := domain.AclMapping{}

		err := db.First(&oldUser, aclmapping.ID).Updates(aclmapping).Error
		if err != nil {
			if strings.Contains(err.Error(), "constraint") {
				return nil, internalerrors.NewViolatedConstraint(err.Error())
			} else {
				return nil, internalerrors.DatabaseError
			}
		}
	} else {
		err := db.Create(&aclmapping).Error
		if err != nil {
			if strings.Contains(err.Error(), "constraint") {
				return nil, internalerrors.NewViolatedConstraint(err.Error())
			} else {
				return nil, internalerrors.DatabaseError
			}
		}
	}

	return aclmapping, nil
}

func (r *AclMappingRepo) DeleteAll(filter *interfaces.Filter) error {
	query, err := r.store.BuildQuery(filter)
	if err != nil {
		return internalerrors.DatabaseError
	}

	err = query.Delete(domain.AclMapping{}).Error
	if err != nil {
		return internalerrors.DatabaseError
	}

	return nil
}

func (r *AclMappingRepo) DeleteByID(id int) error {
	db := r.store.GetDB()

	err := db.Delete(&domain.AclMapping{GormModel: domain.GormModel{ID: id}}).Error
	if err != nil {
		return internalerrors.DatabaseError
	}

	return nil
}
