// Generated by: main
// TypeWriter: access
// Directive: +gen on AclMapping

package ressources

import (
	"github.com/Solher/auth-scaffold/interfaces"
	"github.com/dimfeld/httptreemux"
)

func setAclMappingAccess(routeDir *interfaces.RouteDirectory, controller *AclMappingCtrl) {
	key := interfaces.NewDirectoryKey("aclmappings")
	create := httptreemux.HandlerFunc(controller.Create)
	find := httptreemux.HandlerFunc(controller.Find)
	findByID := httptreemux.HandlerFunc(controller.FindByID)
	upsert := httptreemux.HandlerFunc(controller.Upsert)
	deleteAll := httptreemux.HandlerFunc(controller.DeleteAll)
	deleteByID := httptreemux.HandlerFunc(controller.DeleteByID)
	related := httptreemux.HandlerFunc(controller.Related)
	relatedOne := httptreemux.HandlerFunc(controller.RelatedOne)

	routeDir.Add(key.For("Create"), &interfaces.Route{Method: "POST", Path: "/aclmappings", Handler: &create, Visible: true, CheckPermissions: true})
	routeDir.Add(key.For("Find"), &interfaces.Route{Method: "GET", Path: "/aclmappings", Handler: &find, Visible: true, CheckPermissions: true})
	routeDir.Add(key.For("FindByID"), &interfaces.Route{Method: "GET", Path: "/aclmappings/:id", Handler: &findByID, Visible: true, CheckPermissions: true})
	routeDir.Add(key.For("Upsert"), &interfaces.Route{Method: "PUT", Path: "/aclmappings", Handler: &upsert, Visible: true, CheckPermissions: true})
	routeDir.Add(key.For("DeleteAll"), &interfaces.Route{Method: "DELETE", Path: "/aclmappings", Handler: &deleteAll, Visible: true, CheckPermissions: true})
	routeDir.Add(key.For("DeleteByID"), &interfaces.Route{Method: "DELETE", Path: "/aclmappings/:id", Handler: &deleteByID, Visible: true, CheckPermissions: true})

	routeDir.Add(key.For("CreateRelated"), &interfaces.Route{Method: "POST", Path: "/aclmappings/:pk/:related", Handler: &related, Visible: true, CheckPermissions: false})
	routeDir.Add(key.For("FindRelated"), &interfaces.Route{Method: "GET", Path: "/aclmappings/:pk/:related", Handler: &related, Visible: true, CheckPermissions: false})
	routeDir.Add(key.For("FindByIDRelated"), &interfaces.Route{Method: "GET", Path: "/aclmappings/:pk/:related/:fk", Handler: &relatedOne, Visible: true, CheckPermissions: false})
	routeDir.Add(key.For("UpsertRelated"), &interfaces.Route{Method: "PUT", Path: "/aclmappings/:pk/:related", Handler: &related, Visible: true, CheckPermissions: false})
	routeDir.Add(key.For("DeleteAllRelated"), &interfaces.Route{Method: "DELETE", Path: "/aclmappings/:pk/:related", Handler: &related, Visible: true, CheckPermissions: false})
	routeDir.Add(key.For("DeleteByIDRelated"), &interfaces.Route{Method: "DELETE", Path: "/aclmappings/:pk/:related/:fk", Handler: &relatedOne, Visible: true, CheckPermissions: false})
}
