// Generated by: main
// TypeWriter: interactor
// Directive: +gen on RoleMapping

package ressources

import (
	"github.com/Solher/auth-scaffold/domain"
	"github.com/Solher/auth-scaffold/interfaces"
)

type AbstractRoleMappingRepo interface {
	Create(rolemappings []domain.RoleMapping) ([]domain.RoleMapping, error)
	CreateOne(rolemapping *domain.RoleMapping) (*domain.RoleMapping, error)
	Find(filter *interfaces.Filter) ([]domain.RoleMapping, error)
	FindByID(id int, filter *interfaces.Filter) (*domain.RoleMapping, error)
	Upsert(rolemappings []domain.RoleMapping) ([]domain.RoleMapping, error)
	UpsertOne(rolemapping *domain.RoleMapping) (*domain.RoleMapping, error)
	DeleteAll(filter *interfaces.Filter) error
	DeleteByID(id int) error
}

type RoleMappingInter struct {
	repo AbstractRoleMappingRepo
}

func NewRoleMappingInter(repo AbstractRoleMappingRepo) *RoleMappingInter {
	return &RoleMappingInter{repo: repo}
}

func (i *RoleMappingInter) Create(rolemappings []domain.RoleMapping) ([]domain.RoleMapping, error) {
	rolemappings, err := i.repo.Create(rolemappings)
	return rolemappings, err
}

func (i *RoleMappingInter) CreateOne(rolemapping *domain.RoleMapping) (*domain.RoleMapping, error) {
	rolemapping, err := i.repo.CreateOne(rolemapping)
	return rolemapping, err
}

func (i *RoleMappingInter) Find(filter *interfaces.Filter) ([]domain.RoleMapping, error) {
	rolemappings, err := i.repo.Find(filter)
	return rolemappings, err
}

func (i *RoleMappingInter) FindByID(id int, filter *interfaces.Filter) (*domain.RoleMapping, error) {
	rolemapping, err := i.repo.FindByID(id, filter)
	return rolemapping, err
}

func (i *RoleMappingInter) Upsert(rolemappings []domain.RoleMapping) ([]domain.RoleMapping, error) {
	rolemappings, err := i.repo.Upsert(rolemappings)
	return rolemappings, err
}

func (i *RoleMappingInter) UpsertOne(rolemapping *domain.RoleMapping) (*domain.RoleMapping, error) {
	rolemapping, err := i.repo.UpsertOne(rolemapping)
	return rolemapping, err
}

func (i *RoleMappingInter) DeleteAll(filter *interfaces.Filter) error {
	err := i.repo.DeleteAll(filter)
	return err
}

func (i *RoleMappingInter) DeleteByID(id int) error {
	err := i.repo.DeleteByID(id)
	return err
}
