// Generated by: main
// TypeWriter: hooks
// Directive: +gen on RoleMapping

package ressources

import (
	"time"

	"github.com/Solher/zest/domain"
)

func (i *RoleMappingInter) BeforeCreate(rolemapping *domain.RoleMapping) error {
	rolemapping.ID = 0
	rolemapping.CreatedAt = time.Time{}
	rolemapping.UpdatedAt = time.Time{}

	err := rolemapping.ScopeModel()
	if err != nil {
		return err
	}

	return nil
}

func (i *RoleMappingInter) AfterCreate(rolemapping *domain.RoleMapping) error {
	return nil
}

func (i *RoleMappingInter) BeforeUpdate(rolemapping *domain.RoleMapping) error {
	rolemapping.ID = 0
	rolemapping.CreatedAt = time.Time{}
	rolemapping.UpdatedAt = time.Time{}

	err := rolemapping.ScopeModel()
	if err != nil {
		return err
	}

	return nil
}

func (i *RoleMappingInter) AfterUpdate(rolemapping *domain.RoleMapping) error {
	return nil
}

func (i *RoleMappingInter) BeforeDelete(rolemapping *domain.RoleMapping) error {
	return nil
}

func (i *RoleMappingInter) AfterDelete(rolemapping *domain.RoleMapping) error {
	return nil
}
