// Generated by: main
// TypeWriter: hooks
// Directive: +gen on Role

package ressources

import (
	"time"

	"github.com/Solher/zest/domain"
)

func (i *RoleInter) BeforeCreate(role *domain.Role) error {
	role.ID = 0
	role.CreatedAt = time.Time{}
	role.UpdatedAt = time.Time{}

	err := role.ScopeModel()
	if err != nil {
		return err
	}

	return nil
}

func (i *RoleInter) AfterCreate(role *domain.Role) error {
	return nil
}

func (i *RoleInter) BeforeUpdate(role *domain.Role) error {
	role.ID = 0
	role.CreatedAt = time.Time{}
	role.UpdatedAt = time.Time{}

	err := role.ScopeModel()
	if err != nil {
		return err
	}

	return nil
}

func (i *RoleInter) AfterUpdate(role *domain.Role) error {
	return nil
}

func (i *RoleInter) BeforeDelete(role *domain.Role) error {
	return nil
}

func (i *RoleInter) AfterDelete(role *domain.Role) error {
	return nil
}
