// Generated by: main
// TypeWriter: repository
// Directive: +gen on Role

package ressources

import (
	"strings"

	"github.com/Solher/auth-scaffold/domain"
	"github.com/Solher/auth-scaffold/interfaces"
	"github.com/Solher/auth-scaffold/internalerrors"
)

type RoleRepo struct {
	store interfaces.AbstractGormStore
}

func NewRoleRepo(store interfaces.AbstractGormStore) *RoleRepo {
	return &RoleRepo{store: store}
}

func (r *RoleRepo) Create(roles []domain.Role) ([]domain.Role, error) {
	db := r.store.GetDB()
	transaction := db.Begin()

	for i, role := range roles {
		err := db.Create(&role).Error
		if err != nil {
			transaction.Rollback()

			if strings.Contains(err.Error(), "constraint") {
				return nil, internalerrors.NewViolatedConstraint(err.Error())
			} else {
				return nil, internalerrors.DatabaseError
			}
		}

		roles[i] = role
	}

	transaction.Commit()
	return roles, nil
}

func (r *RoleRepo) CreateOne(role *domain.Role) (*domain.Role, error) {
	db := r.store.GetDB()

	err := db.Create(role).Error
	if err != nil {
		if strings.Contains(err.Error(), "constraint") {
			return nil, internalerrors.NewViolatedConstraint(err.Error())
		} else {
			return nil, internalerrors.DatabaseError
		}
	}

	return role, nil
}

func (r *RoleRepo) Find(filter *interfaces.Filter) ([]domain.Role, error) {
	query, err := r.store.BuildQuery(filter)
	if err != nil {
		return nil, internalerrors.DatabaseError
	}

	roles := []domain.Role{}

	err = query.Find(&roles).Error
	if err != nil {
		return nil, internalerrors.DatabaseError
	}

	return roles, nil
}

func (r *RoleRepo) FindByID(id int, filter *interfaces.Filter) (*domain.Role, error) {
	query, err := r.store.BuildQuery(filter)
	if err != nil {
		return nil, internalerrors.DatabaseError
	}

	role := domain.Role{}

	err = query.First(&role, id).Error
	if err != nil {
		return nil, internalerrors.DatabaseError
	}

	return &role, nil
}

func (r *RoleRepo) Upsert(roles []domain.Role) ([]domain.Role, error) {
	db := r.store.GetDB()
	transaction := db.Begin()

	for i, role := range roles {
		if role.ID != 0 {
			oldUser := domain.Role{}

			err := db.First(&oldUser, role.ID).Updates(role).Error
			if err != nil {
				transaction.Rollback()

				if strings.Contains(err.Error(), "constraint") {
					return nil, internalerrors.NewViolatedConstraint(err.Error())
				} else {
					return nil, internalerrors.DatabaseError
				}
			}
		} else {
			err := db.Create(&role).Error
			if err != nil {
				transaction.Rollback()

				if strings.Contains(err.Error(), "constraint") {
					return nil, internalerrors.NewViolatedConstraint(err.Error())
				} else {
					return nil, internalerrors.DatabaseError
				}
			}
		}

		roles[i] = role
	}

	transaction.Commit()
	return roles, nil
}

func (r *RoleRepo) UpsertOne(role *domain.Role) (*domain.Role, error) {
	db := r.store.GetDB()

	if role.ID != 0 {
		oldUser := domain.Role{}

		err := db.First(&oldUser, role.ID).Updates(role).Error
		if err != nil {
			if strings.Contains(err.Error(), "constraint") {
				return nil, internalerrors.NewViolatedConstraint(err.Error())
			} else {
				return nil, internalerrors.DatabaseError
			}
		}
	} else {
		err := db.Create(&role).Error
		if err != nil {
			if strings.Contains(err.Error(), "constraint") {
				return nil, internalerrors.NewViolatedConstraint(err.Error())
			} else {
				return nil, internalerrors.DatabaseError
			}
		}
	}

	return role, nil
}

func (r *RoleRepo) DeleteAll(filter *interfaces.Filter) error {
	query, err := r.store.BuildQuery(filter)
	if err != nil {
		return internalerrors.DatabaseError
	}

	err = query.Delete(domain.Role{}).Error
	if err != nil {
		return internalerrors.DatabaseError
	}

	return nil
}

func (r *RoleRepo) DeleteByID(id int) error {
	db := r.store.GetDB()

	err := db.Delete(&domain.Role{GormModel: domain.GormModel{ID: id}}).Error
	if err != nil {
		return internalerrors.DatabaseError
	}

	return nil
}
