// Generated by: main
// TypeWriter: access
// Directive: +gen on Session

package ressources

import (
	"github.com/Solher/auth-scaffold/interfaces"
	"github.com/dimfeld/httptreemux"
)

func setSessionAccessOptions(routeDir *interfaces.RouteDirectory, controller *SessionCtrl) {
	key := interfaces.NewDirectoryKey("sessions")
	create := httptreemux.HandlerFunc(controller.Create)
	find := httptreemux.HandlerFunc(controller.Find)
	findByID := httptreemux.HandlerFunc(controller.FindByID)
	upsert := httptreemux.HandlerFunc(controller.Upsert)
	deleteAll := httptreemux.HandlerFunc(controller.DeleteAll)
	deleteByID := httptreemux.HandlerFunc(controller.DeleteByID)

	routeDir.Add(key.For("Create"), &interfaces.Route{Method: "POST", Path: "/sessions", Handler: &create, Visible: true}, true)
	routeDir.Add(key.For("Find"), &interfaces.Route{Method: "GET", Path: "/sessions", Handler: &find, Visible: true}, true)
	routeDir.Add(key.For("FindByID"), &interfaces.Route{Method: "GET", Path: "/sessions/:id", Handler: &findByID, Visible: true}, true)
	routeDir.Add(key.For("Upsert"), &interfaces.Route{Method: "PUT", Path: "/sessions", Handler: &upsert, Visible: true}, true)
	routeDir.Add(key.For("DeleteAll"), &interfaces.Route{Method: "DELETE", Path: "/sessions", Handler: &deleteAll, Visible: true}, true)
	routeDir.Add(key.For("DeleteByID"), &interfaces.Route{Method: "DELETE", Path: "/sessions/:id", Handler: &deleteByID, Visible: true}, true)
}
