// Generated by: main
// TypeWriter: hooks
// Directive: +gen on User

package ressources

import (
	"time"

	"github.com/Solher/zest/domain"
)

func (i *UserInter) BeforeCreate(user *domain.User) error {
	user.ID = 0
	user.CreatedAt = time.Time{}
	user.UpdatedAt = time.Time{}

	err := user.ScopeModel()
	if err != nil {
		return err
	}

	return nil
}

func (i *UserInter) AfterCreate(user *domain.User) error {
	return nil
}

func (i *UserInter) BeforeUpdate(user *domain.User) error {
	user.ID = 0
	user.CreatedAt = time.Time{}
	user.UpdatedAt = time.Time{}

	err := user.ScopeModel()
	if err != nil {
		return err
	}

	return nil
}

func (i *UserInter) AfterUpdate(user *domain.User) error {
	return nil
}

func (i *UserInter) BeforeDelete(user *domain.User) error {
	return nil
}

func (i *UserInter) AfterDelete(user *domain.User) error {
	return nil
}
