// Generated by: main
// TypeWriter: routes
// Directive: +gen on User

package ressources

import "github.com/Solher/auth-scaffold/interfaces"

func addUserRoutes(routesDir interfaces.RouteDirectory, controller *UserCtrl) {
	key := interfaces.NewDirectoryKey(controller)

	routesDir[key.For("Create")] = interfaces.Route{Method: "POST", Path: "/users", Handler: controller.Create}
	routesDir[key.For("Find")] = interfaces.Route{Method: "GET", Path: "/users", Handler: controller.Find}
	routesDir[key.For("FindByID")] = interfaces.Route{Method: "GET", Path: "/users/:id", Handler: controller.FindByID}
	routesDir[key.For("Upsert")] = interfaces.Route{Method: "PUT", Path: "/users", Handler: controller.Upsert}
	routesDir[key.For("DeleteAll")] = interfaces.Route{Method: "DELETE", Path: "/users", Handler: controller.DeleteAll}
	routesDir[key.For("DeleteByID")] = interfaces.Route{Method: "DELETE", Path: "/users/:id", Handler: controller.DeleteByID}
}
