// Generated by: main
// TypeWriter: controller
// Directive: +gen on User

package ressources

import (
	"encoding/json"
	"io/ioutil"
	"net/http"
	"strconv"

	"github.com/Solher/auth-scaffold/apierrors"
	"github.com/Solher/auth-scaffold/domain"
	"github.com/Solher/auth-scaffold/interfaces"
	"github.com/Solher/auth-scaffold/internalerrors"
	"github.com/dimfeld/httptreemux"
	"github.com/gorilla/context"
)

type AbstractUserInter interface {
	Create(users []domain.User) ([]domain.User, error)
	CreateOne(user *domain.User) (*domain.User, error)
	Find(filter *interfaces.Filter) ([]domain.User, error)
	FindByID(id int, filter *interfaces.Filter) (*domain.User, error)
	Upsert(users []domain.User) ([]domain.User, error)
	UpsertOne(user *domain.User) (*domain.User, error)
	DeleteAll(filter *interfaces.Filter) error
	DeleteByID(id int) error
}

type UserCtrl struct {
	interactor AbstractUserInter
	render     interfaces.AbstractRender
	routeDir   *interfaces.RouteDirectory
}

func NewUserCtrl(interactor AbstractUserInter, render interfaces.AbstractRender, routeDir *interfaces.RouteDirectory) *UserCtrl {
	controller := &UserCtrl{interactor: interactor, render: render, routeDir: routeDir}

	if routeDir != nil {
		setUserAccessOptions(routeDir, controller)
	}

	return controller
}

func (c *UserCtrl) Create(w http.ResponseWriter, r *http.Request, _ map[string]string) {
	user := &domain.User{}
	var users []domain.User

	buffer, _ := ioutil.ReadAll(r.Body)

	err := json.Unmarshal(buffer, user)
	if err != nil {
		err := json.Unmarshal(buffer, &users)
		if err != nil {
			c.render.JSONError(w, http.StatusBadRequest, apierrors.BodyDecodingError, err)
			return
		}
	}

	lastRessource := interfaces.GetLastRessource(r)

	if users == nil {
		user.ScopeModel(lastRessource.ID)
		user, err = c.interactor.CreateOne(user)
	} else {
		for i := range users {
			(&users[i]).ScopeModel(lastRessource.ID)
		}
		users, err = c.interactor.Create(users)
	}

	if err != nil {
		switch err.(type) {
		case *internalerrors.ViolatedConstraint:
			c.render.JSONError(w, 422, apierrors.ViolatedConstraint, err)
		default:
			c.render.JSONError(w, http.StatusInternalServerError, apierrors.InternalServerError, err)
		}
		return
	}

	if users == nil {
		c.render.JSON(w, http.StatusCreated, user)
	} else {
		c.render.JSON(w, http.StatusCreated, users)
	}
}

func (c *UserCtrl) Find(w http.ResponseWriter, r *http.Request, _ map[string]string) {
	filter, err := interfaces.GetQueryFilter(r)
	if err != nil {
		c.render.JSONError(w, http.StatusBadRequest, apierrors.FilterDecodingError, err)
		return
	}

	filter = interfaces.FilterIfLastRessource(r, filter)

	users, err := c.interactor.Find(filter)
	if err != nil {
		c.render.JSONError(w, http.StatusInternalServerError, apierrors.InternalServerError, err)
		return
	}

	c.render.JSON(w, http.StatusOK, users)
}

func (c *UserCtrl) FindByID(w http.ResponseWriter, r *http.Request, params map[string]string) {
	id, err := strconv.Atoi(params["id"])
	if err != nil {
		c.render.JSONError(w, http.StatusBadRequest, apierrors.InvalidPathParams, err)
		return
	}

	filter, err := interfaces.GetQueryFilter(r)
	if err != nil {
		c.render.JSONError(w, http.StatusBadRequest, apierrors.FilterDecodingError, err)
		return
	}

	user, err := c.interactor.FindByID(id, filter)
	if err != nil {
		c.render.JSONError(w, http.StatusUnauthorized, apierrors.Unauthorized, err)
		return
	}

	c.render.JSON(w, http.StatusOK, user)
}

func (c *UserCtrl) Upsert(w http.ResponseWriter, r *http.Request, _ map[string]string) {
	user := &domain.User{}
	var users []domain.User

	buffer, _ := ioutil.ReadAll(r.Body)

	err := json.Unmarshal(buffer, user)
	if err != nil {
		err := json.Unmarshal(buffer, &users)
		if err != nil {
			c.render.JSONError(w, http.StatusBadRequest, apierrors.BodyDecodingError, err)
			return
		}
	}

	lastRessource := interfaces.GetLastRessource(r)

	if users == nil {
		user.ScopeModel(lastRessource.ID)
		user, err = c.interactor.UpsertOne(user)
	} else {
		for i := range users {
			(&users[i]).ScopeModel(lastRessource.ID)
		}
		users, err = c.interactor.Upsert(users)
	}

	if err != nil {
		switch err.(type) {
		case *internalerrors.ViolatedConstraint:
			c.render.JSONError(w, 422, apierrors.ViolatedConstraint, err)
		default:
			c.render.JSONError(w, http.StatusInternalServerError, apierrors.InternalServerError, err)
		}
		return
	}

	if users == nil {
		c.render.JSON(w, http.StatusCreated, user)
	} else {
		c.render.JSON(w, http.StatusCreated, users)
	}
}

func (c *UserCtrl) DeleteAll(w http.ResponseWriter, r *http.Request, _ map[string]string) {
	filter, err := interfaces.GetQueryFilter(r)
	if err != nil {
		c.render.JSONError(w, http.StatusBadRequest, apierrors.FilterDecodingError, err)
		return
	}

	filter = interfaces.FilterIfLastRessource(r, filter)

	err = c.interactor.DeleteAll(filter)
	if err != nil {
		c.render.JSONError(w, http.StatusInternalServerError, apierrors.InternalServerError, err)
		return
	}

	c.render.JSON(w, http.StatusNoContent, nil)
}

func (c *UserCtrl) DeleteByID(w http.ResponseWriter, r *http.Request, params map[string]string) {
	id, err := strconv.Atoi(params["id"])
	if err != nil {
		c.render.JSONError(w, http.StatusBadRequest, apierrors.InvalidPathParams, err)
		return
	}

	err = c.interactor.DeleteByID(id)
	if err != nil {
		c.render.JSONError(w, http.StatusUnauthorized, apierrors.Unauthorized, err)
		return
	}

	c.render.JSON(w, http.StatusNoContent, nil)
}

func (c *UserCtrl) Related(w http.ResponseWriter, r *http.Request, params map[string]string) {
	pk, err := strconv.Atoi(params["pk"])
	if err != nil {
		c.render.JSONError(w, http.StatusBadRequest, apierrors.InvalidPathParams, err)
		return
	}

	related := params["related"]
	key := interfaces.NewDirectoryKey(related)

	var handler *httptreemux.HandlerFunc
	switch r.Method {
	case "POST":
		handler = c.routeDir.Get(key.For("Create")).Handler
	case "GET":
		handler = c.routeDir.Get(key.For("Find")).Handler
	case "PUT":
		handler = c.routeDir.Get(key.For("Upsert")).Handler
	case "DELETE":
		handler = c.routeDir.Get(key.For("DeleteAll")).Handler
	}

	if handler == nil {
		c.render.JSON(w, http.StatusNotFound, nil)
		return
	}

	context.Set(r, "lastRessource", &interfaces.Ressource{Name: related, IDKey: "userID", ID: pk})

	(*handler)(w, r, params)
}

func (c *UserCtrl) RelatedOne(w http.ResponseWriter, r *http.Request, params map[string]string) {
	params["id"] = params["fk"]

	related := params["related"]
	key := interfaces.NewDirectoryKey(related)

	var handler httptreemux.HandlerFunc

	switch r.Method {
	case "GET":
		handler = *c.routeDir.Get(key.For("FindByID")).Handler
	case "DELETE":
		handler = *c.routeDir.Get(key.For("DeleteByID")).Handler
	}

	if handler == nil {
		c.render.JSON(w, http.StatusNotFound, nil)
		return
	}

	handler(w, r, params)
}
